// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4DMLn6O_ZR3zdoinYKrbSKy-5NjManyM',
    appId: '1:66402460564:web:a8026947cc16e145b3a581',
    messagingSenderId: '66402460564',
    projectId: 'dgbitirme-ac4b4',
    authDomain: 'dgbitirme-ac4b4.firebaseapp.com',
    storageBucket: 'dgbitirme-ac4b4.appspot.com',
    measurementId: 'G-LYXPNBSL35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDpqZK1LLS7WP-KVRGp6uEpY4FrNgnGGs',
    appId: '1:66402460564:android:6e1ed7a1dfa30d0cb3a581',
    messagingSenderId: '66402460564',
    projectId: 'dgbitirme-ac4b4',
    storageBucket: 'dgbitirme-ac4b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgoY0eCK7Bq-BSXNVPpb9A3P1ffiZPxmg',
    appId: '1:66402460564:ios:d90a0094441f04c1b3a581',
    messagingSenderId: '66402460564',
    projectId: 'dgbitirme-ac4b4',
    storageBucket: 'dgbitirme-ac4b4.appspot.com',
    iosBundleId: 'com.example.dgbitirme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgoY0eCK7Bq-BSXNVPpb9A3P1ffiZPxmg',
    appId: '1:66402460564:ios:03f33e130fc4c41ab3a581',
    messagingSenderId: '66402460564',
    projectId: 'dgbitirme-ac4b4',
    storageBucket: 'dgbitirme-ac4b4.appspot.com',
    iosBundleId: 'com.example.dgbitirme.RunnerTests',
  );
}
